name: Clojure CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [11, 17, 24]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: latest
    
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-m2-
    
    - name: Run tests
      run: lein test
